### ISSUE TITLE
06. Helm Options : Update helm release name

### ISSUE THREAD

**Issue by MohamedBenighil** [mabusaa/argocd-course-issues-tracker#13]
Hello Mohamed,

i would like just to thank you about your great course : ma sha Allah 

Just i have a remarqu on Lab : 06. "Helm Options : Update helm release name", i guess when you click on "check" button, you get "failed" message even if everything is correct.

regards : )

**Comment by mabusaa** [comment]
Hi,
Thank you , I will give it a try and verify that

**Comment by mabusaa** [comment]
I just tried the entire lab , its working perfectly , can you please provide me steps to reproduce it

**Comment by sergiosanche** [comment]
Hello!

I am facing the same issue.

Regards.

**Comment by mabusaa** [comment]
Hi @sergiosanche 

can you please provide me with your application yaml that you applied.

**Comment by cod3mas0n** [comment]
hello @mabusaa 
I have the same issue, the YAML manifest of the Argo application is okay, even with the provided solution it returns false status in its verification API request

even applied the provided solution, to ensure not to misspelled the names or ....
 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: helm-app
  namespace: argocd
spec: 
  destination: 
    namespace: helm-app
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: helm-guestbook
    repoURL: "https://github.com/mabusaa/argocd-example-apps.git"
    targetRevision: master
    helm:
     releaseName: my-release
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```
