### ISSUE TITLE
istio example: the server could not find the requested resource

### ISSUE THREAD

**Issue by kevingigiano** [mabusaa/argocd-course-issues-tracker#23]
When running through _Practice (Interactive) - Diffing Customization , Istio Case_, I ran into  an issue where none of the istio resources could be found for the version specified.

**Environment:**
Minikube v1.30.1
CentOS 8

**Error:**
_the server could not find the requested resource_

**Workaround:**
Update this: 
`targetRevision: '1.13.4'` --> `targetRevision: '*' `

Upon changing the `targetRevision`, the deployment worked as expected, with the exception, `ignoreDifferences` wasn't required to sync and deploy properly.
Based on YAML below, istio 1.18.0 got deployed.

**Working ArgoCD Application:**
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: "https://kubernetes.default.svc"
  project: default
  source:
    chart: istiod
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: '*'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
```
