### ISSUE TITLE
ArgoCD CONNECTION FAILED in private repository exercise

### ISSUE THREAD

**Issue by okm1997** [mabusaa/argocd-course-issues-tracker#25]
In "https://killercoda.com/mabusaa/course/argocd-endusers-scenarios/11-private-repos-https"  exercise.
CONNECTION STATUS = Failed. I can't seem to understand 

repo.yml

```
apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/user/checkargo.git
  password: token from github
  username: token name from github
```
