### ISSUE TITLE
How can I connect lab argocd to an AWS EKS cluster

### ISSUE THREAD

**Issue by zs856** [mabusaa/argocd-course-issues-tracker#4]
Hi, I created a cluster on AWS EKS. However, I am not sure of the steps to connect it. I wonder whether you can give me some support? I have spent hours on the Internet to find tutorials on connecting Argocd to an AWS cluster, but I did not find anything useful.

**Comment by mabusaa** [comment]
the simplest approach is to use bearer token , 

1. create k8s service account , `kubectl create sa eks-admin`
2. map the service account with the cluster admin role 
example: 
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: eks-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: eks-admin
  namespace: default
```
3. obtain the service account token `kubectl describe secrets/eks-admin-secret.....etc` , get the token .
4. create the cluster in argocd declaratively and set the token in beaerToken field and api url of ur cluster.
example: https://github.com/mabusaa/argocd-course-apps-definitions/blob/main/clusters/staging-digitalocean.yaml
